name: NodeJS CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ sucess() }}
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ sucess() }}
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: | 
      echo "Test status ${{needs.build.status}}"
